#Resource Icon, 1, ".\GFX\Pause.ico"
#Resource Manifest 1, "Wait.exe.manifest"

#Resource VersionInfo

#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Wait amount of seconds or keypress."
#Resource Version$ "LegalCopyright",   "Copyright 2017-2022 Knuth Konrad"
#Resource Version$ "OriginalFilename", "Wait.exe"
#Resource Version$ "ProductName",      "Wait"
#Resource Version$ "ProductVersion",   "1.0.3.0"
#Resource Version$ "FileVersion",      "1.0.3.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
